version: '3'
services:
  web:
    ports:
    - "80:80"
    volumes:
    - ./web:/usr/local/apache2/htdocs
    image: httpd
  api:
    build:
      context: ./api
      args: 
        project_directory: "/projects/"
    command: flask run --host 0.0.0.0 --port 9000
    volumes:
    - ./api:/projects
    ports:
    - "9000:9000"
    tty: true
  redis:
    volumes:
    - ./db:/data
    image: redis
volumes:
  logvolume01: {}